/**
 * Generated by tsnapi — public API snapshot of `volcengine-ai-mediakit`
 */
// #region Interfaces
export interface ApiResponse<T = unknown> {
  success: boolean;
  task_id?: string;
  request_id: string;
  task_type?: string;
  status?: string;
  result?: T;
  expires_at?: number;
  created_at?: number;
  finished_at?: number;
}
export interface CreateTaskResponse {
  success: boolean;
  task_id: string;
  request_id: string;
}
export interface EnhanceVideoParams {
  video_url: string;
  scene?: 'aigc' | 'short_series' | 'ugc' | 'old_film';
  tool_version?: 'standard' | 'professional';
  resolution?: '720p' | '1080p' | '4k';
  resolution_limit?: number;
  fps?: number;
}
export interface EnhanceVideoResult {
  duration: number;
  fps: number;
  resolution: string;
  tool_version: string;
  video_url: string;
}
export interface MediakitConfig {
  apiKey: string;
  baseURL?: string;
}
export interface RequestConfig extends AxiosRequestConfig {
  apiKey?: string;
}
export interface TaskResult<T = unknown> {
  success: boolean;
  task_id: string;
  task_type?: string;
  status: TaskStatus;
  result?: T;
  expires_at?: number;
  created_at?: number;
  finished_at?: number;
  request_id: string;
}
export interface WaitForTaskOptions {
  interval?: number;
  timeout?: number;
  onProgress?: (_: TaskResult) => void;
}
// #endregion

// #region Types
export type TaskStatus = 'pending' | 'running' | 'completed' | 'failed';
// #endregion

// #region Classes
export declare class ApiError extends Error {
  readonly status: number;
  readonly data?: unknown | undefined;
  name: string;
  constructor(_: string, _: number, _?: unknown | undefined);
}
export declare class HttpClient {
  private client;
  private apiKey?;
  constructor(_?: string);
  setApiKey(_: string): void;
  getApiKey(): string | undefined;
  get<T = unknown>(_: string, _?: RequestConfig): Promise<ApiResponse<T>>;
  post<T = unknown>(_: string, _?: unknown, _?: RequestConfig): Promise<ApiResponse<T>>;
  request<T = unknown>(_: AxiosRequestConfig & {
    apiKey?: string;
  }): Promise<ApiResponse<T>>;
}
export declare class Mediakit {
  private client;
  constructor(_: MediakitConfig);
  getTask(_: string): Promise<TaskResult<unknown>>;
  waitForTask(_: string, _?: Parameters<typeof waitForTask>[2]): Promise<TaskResult<unknown>>;
  enhanceVideo(_: Parameters<typeof enhanceVideo>[1]): Promise<CreateTaskResponse>;
  enhanceVideoAndWait(_: Parameters<typeof enhanceVideoAndWait>[1], _?: Parameters<typeof enhanceVideoAndWait>[2]): Promise<TaskResult<EnhanceVideoResult>>;
}
// #endregion

// #region Functions
export declare function enhanceVideo(_: HttpClient, _: EnhanceVideoParams): Promise<CreateTaskResponse>;
export declare function enhanceVideoAndWait(_: HttpClient, _: EnhanceVideoParams, _?: WaitForTaskOptions): Promise<TaskResult<EnhanceVideoResult>>;
export declare function getTask(_: HttpClient, _: string): Promise<TaskResult>;
export declare function setApiKey(_: string): void;
export declare function waitForTask(_: HttpClient, _: string, _?: WaitForTaskOptions): Promise<TaskResult>;
// #endregion

// #region Variables
export declare const http: {
  get: <T>(url: string, config?: RequestConfig) => Promise<ApiResponse<T>>;
  post: <T>(url: string, body?: unknown, config?: RequestConfig) => Promise<ApiResponse<T>>;
};
// #endregion